---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/dheles/ansible-role-login-user
  name: login-user

- src: https://github.com/dheles/ansible-role-secure-ssh
  name: secure-ssh

- src: https://github.com/dheles/deploy-keys-ansible-role
  name: deploy-keys

- src: https://github.com/dheles/ansible-role-java.git
  name: java

- src: https://github.com/dheles/ansible-role-apache.git
  name: apache

- src: https://github.com/farooqsadiq/ansible-role-passenger.git
  name: passenger

- src: https://github.com/dheles/ansible-chruby.git
  name: chruby

- src: https://github.com/jhu-sheridan-libraries/ansible-role-mysql
  name: mysql

- src: https://github.com/dheles/jetty-ansible-role
  name: jetty

- src: https://github.com/farooqsadiq/shibboleth-sp-ansible-role
  name: shib

- src: https://github.com/dheles/firewalld-ansible-role
  name: firewalld

- src: https://github.com/dheles/bantheman-ansible-role
  name: bantheman

- src: https://github.com/dheles/logrotate-ansible-role
  name: logrotate

- src: https://github.com/dheles/testup-ansible-role
  name: testup

- src: https://github.com/dheles/solr-ansible-role
  name: solr

- src: https://github.com/dheles/fail2ban-ansible-role
  name: fail2ban

- src: https://github.com/geerlingguy/ansible-role-nodejs
  name: ansible-role-nodejs
