---
- name: install catalyst rails application
  hosts: catalyst

  pre_tasks:
  - name: install required packages
    package:
      name: "{{ item }}"
      state: present
    become: true
    with_items:
      - http-parser
      - 'nodejs'
      - "@Development tools"
      - mysql-devel

  - name: ensure that yarn is installed
    block:
      - name: see if yarn is present
        command: yarn -v
    rescue:
    - name: install yarn
      shell:
        cmd: npm install yarn -g
        become: true

  - name: include apache role to get its handlers
    include_role:
      name: apache
      tasks_from: dolittle

  tasks:
  - name: configure application user
    include_tasks: configure_app_user.yml

  - name: make sure deploy dir exists
    file:
      path: "{{ deploy_dir }}"
      owner: "{{ app_name }}"
      group: "{{ app_name }}"
      mode: g+w
      state: directory
      recurse: true
    become: true

  - name: get application from repo
    git:
      repo: "{{ app_repo }}"
      dest: "{{ ansible_env.HOME }}/{{ app_name }}"
      version: "{{ app_branch | default('HEAD') }}"
      key_file: "{{ catalyst_deploy_key_full_path }}"
      ssh_opts: "-o StrictHostKeyChecking=no"

  - name: ensure capistrano is installed
    block:
      - name: see if cap is present
        command: bundle exec cap -v
    rescue:
    - name: run bundle install to get cap
      shell:
        chdir: "{{ ansible_env.HOME }}/{{ app_name }}"
        cmd: bundle install

  - name: ensure webpack is installed
    block:
      - name: see if webpack is present
        shell:
          chdir: "{{ ansible_env.HOME }}/{{ app_name }}"
          cmd: "./bin/weback -v"
    rescue:
      - name: install yarn dependencies to get webpack
        shell:
          chdir: "{{ deploy_dir }}"
          cmd: "yarn install"

  - name: cap deploy
    shell:
      chdir: "{{ ansible_env.HOME }}/{{ app_name }}"
      cmd: "BRANCH={{ app_branch }} bundle exec cap localhost deploy"

  - name: generate rails secret_key_base
    # TODO: use or lose
    # command: bash -lc "bundle exec rake secret"
    command: "openssl rand -hex 64"
    register: secret_key_base_result
    no_log: "{{ not debugging }}"

  - name: set secret_key_base
    set_fact:
      secret_key_base: "{{ secret_key_base_result.stdout }}"

  - name: Configure environment variables
    no_log: "{{ not debugging }}"
    template:
      src:  "templates/dotenv.j2"
      dest:  "{{ deploy_dir }}/.env"
    notify: restart apache

  - name: insert catalyst configs into virtualhost config
    blockinfile:
      block:  "{{ lookup('template', 'templates/catalyst_virtualhost.j2') }}"
      dest: "{{ apache_config_file }}"
      marker: "# {mark} catalyst configs"
      insertbefore: "</VirtualHost>"
    notify: restart apache
    become: true

  # - name: make sure that apache uses the capistrano deploy directory
  #   lineinfile:
  #     path: "{{ apache_config_file }}"
  #     regexp: '^DocumentRoot '
  #     insertafter: '^#DocumentRoot '
  #     line: 'DocumentRoot "{{ passenger_deploy_dir }}"'
  #   notify: restart apache
  #   become: true

  # - name: ensure that apache uses the correct security settings on the catalyst directory
  #   lineinfile:
  #     path: "{{ apache_config_file }}"
  #     regexp: '^Directory '
  #     insertafter: '^#Directory '
  #     line: 'Directory "{{ passenger_deploy_dir }}"'
  #   notify: restart apache
  #   become: true

  - name: override default http redirect in virtualhost config
    blockinfile:
      block:  "{{ lookup('template', 'templates/http_redirect.j2') }}"
      dest: "{{ apache_config_file }}"
      marker: "# {mark} {{ apache_http_redirect_marker }}"
      insertafter: "<VirtualHost *:80>"
    notify: restart apache
    become: true
