---
- hosts: catalyst
  # connection: local

  vars:
    rubies:
      - "ruby-2.2.2"
      - "jruby-9.2.13"
      - "jruby-9.2.13.0"
      - "jruby"

  tasks:
    - include: test_regex.yml
      with_items: "{{ rubies }}"
